Either/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

Either/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path(
        '<int:article_pk>/comments/<int:comment_pk>/delete/',
        views.comments_delete,
        name='comments_delete',
    ),
    path('random/', views.random, name='random'),
]

Either/either/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('what_are_your_choices/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

Either/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

Either/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
        )

Either/articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
        # exclude = ('author',)
        widgets = {
            'img': forms.Textarea(attrs={'style': 'height: 50px;width:250px'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ('article',)

Either/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserCreationForm, CustomUserChangeForm


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        # form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {'form': form}
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('articles:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('articles:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        # form = CustomUserChangeForm(data=request.POST, instance=request.user)
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        # form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

Either/articles/views.py
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import (
    require_http_methods,
    require_POST,
    require_safe,
)
import random as lib_random

# Create your views here.
@require_safe
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    # print(form.errors)
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


@require_safe
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    total = comments.count()
    blue_team = comments.filter(team=True).count()
    red_team = comments.filter(team=False).count()
    if total != 0:
        blue_rate = round((blue_team / total) * 100, 1)
        red_rate = round((red_team / total) * 100, 1)
    else:
        blue_rate = 0
        red_rate = 0
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
        'total': total,
        'blue_team': blue_team,
        'red_team': red_team,
        'blue_rate': blue_rate,
        'red_rate': red_rate,
    }
    return render(request, 'articles/detail.html', context)


@require_POST
def delete(request, pk):
    if request.user.is_authenticated:
        article = Article.objects.get(pk=pk)
        article.delete()
    return redirect('articles:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)


def comments_create(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.save()
    return redirect('articles:detail', article.pk)


def comments_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('articles:detail', article_pk)


def random(request):
    articles = Article.objects.all()
    id_arr = [article.pk for article in articles]
    pk = lib_random.choice(id_arr)
    return redirect('articles:detail', pk)

Either/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>
    {% for s in 'New Game' %}
      <span>{{ s }}</span>
    {% endfor %}
  </h1>
  {% comment %} <h1>New Game</h1> {% endcomment %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">CREATE</button>
  </form>
  <hr>
{% endblock content %}

Either/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center header fw-bold">
    {% comment %} {{ article.title }} {% endcomment %}
    {% for s in article.title %}
      <span>{{ s }}</span>
    {% endfor %}
  </h1>
  <hr>
  <div class="d-flex flex-row">
    <h4 class="me-auto px-2 bold text-primary text-opacity-75">{{ article.content1 }}</h4>
    <h4 class="px-2 bold text-danger text-opacity-75">{{ article.content2 }}</h4>
  </div>
  <div class="progress">
    <div class="progress-bar progress-bar-striped progress-bar-animated progress-bar-transition" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: {{ blue_rate }}%">{{ blue_rate }}%</div>
    <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: {{ red_rate }}%">{{ red_rate }}%</div>
  </div>
  <br>
  {% if request.user.is_authenticated %}
    <div class='d-flex flex-row-reverse'>
      <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">삭제</button>
      </form>
      <button type="button" onclick="location.href='{% url 'articles:update' article.pk %}' " class="btn btn-primary mx-2">수정</button>
    </div>
  {% endif %}
  <hr>

  <div class="d-flex">
    {% comment %} <h4>댓글 작성</h4> {% endcomment %}
  </div>
  <div class="">
    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
      {% csrf_token %}
      <div style="width:100%">
        <label for="team" class="d-flex">선택</label>
        <select name="team" id="team" style="width:100%; height:30px">
          <option value=True>{{ article.content1 }}</option>
          <option value=False>{{ article.content2 }}</option>
        </select>
      </div>
      <br>
      <label for="content" class="d-flex">이유</label>
      <input type="text" name="content" id="content"  style="width:100%; height:30px">
      <br>
      <button type="submit" class="d-flex btn btn-secondary mt-4">선택</button>
    </form>
  </div>
  <hr>
  <h4>목록</h4>
  <ul>
    {% for comment in comments %}
    {% if comment.team == True %}
    <div class="d-flex">
      <div class="d-flex flex-row w-100 p-2 m-2 bg-info bg-opacity-25 rounded ">
        {{ comment.content }}
      </div>
      <div class="p-2"></div>
    </div>
    {% else %}
      <div class="d-flex">
        <div class="p-2"></div>
        <div class="d-flex flex-row-reverse p-2 w-100 p-2 m-2 bg-danger bg-opacity-25 rounded ">
          {{ comment.content }}
        </div>
      </div>
    {% endif %}
    {% endfor %}
  </ul>
  <hr>

{% endblock content %}

Either/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %} 
  <div style="height:50px">
    {% if request.user.is_authenticated %}
      <button type="button" onclick="location.href='{% url 'articles:create' %}' " class="btn btn-primary mx-2">New Game</button>
      <button type="button" onclick="location.href='{% url 'articles:random' %}' " class="btn btn-danger mx-2">Random Game</button>
    {% else %}
      <div class="d-flex justify-content-center">
        <a href="{% url 'accounts:login' %}" class="text-decoration-none">
          <h4>
            로그인하고 새로운 게임을 만드세요!
          </h4>
          </a>
      </div>
    {% endif %}
  </div>
  <hr class="mb-5">
  <div class="pb-5">
    <section class="container">
      <div class="d-flex justify-content-around row row-cols-1 row-cols-sm-3 g-4">
        {% for article in articles %}
          <a href="{% url 'articles:detail' article.pk %}" style="text-decoration: none; color: black; width:30%; height:40%;">
            <article class="col" style="">
              <div class="card scale-up-center">
                <img src="{{ article.img }}" class="card-img-top img-fluid" alt="Img" style="width:100%; height:170px">
                <div class="card-body">
                  <h5 class="card-title">{{ article.title }}</h5>
                  <p class="card-text">{{ article.content1 }} VS {{ article.content2 }}</p>
                </div>
              </div>
            </article>
          </a>
        {% endfor %}
      </div>
    </section>
  </div>
{% endblock content %}

Either/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}